import {Cloud,beginGoogle,configured,projectURL} from './auth.js';
const $=id=>document.getElementById(id);let members=[],me=null;
const extension=Boolean(globalThis.chrome?.runtime?.id);
const cloud=new Cloud({get:async()=>JSON.parse(sessionStorage.getItem('ledgerSession')||'null'),set:async value=>value?sessionStorage.setItem('ledgerSession',JSON.stringify(value)):sessionStorage.removeItem('ledgerSession')});
const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
const map={ledger_me:'refreshProfile',ledger_admin_data:'adminData',ledger_inbox:'inbox',ledger_my_requests:'myRequests',ledger_request_admin:'requestAdmin',ledger_decide_admin:'decideAdmin',ledger_set_admin:'setAdmin',ledger_read_notice:'readNotice'};
async function rpc(name,args={}){if(!extension)return cloud.rpc(name,args);const r=await chrome.runtime.sendMessage({type:map[name],args});if(r.error)throw Error(r.error);return r.data;}
async function act(f){try{$('message').textContent='';await f();}catch(e){$('message').textContent=e.message;}}
async function load(){
 // Server checks every request. Never infer administrator rights from Google profile metadata.
 me=await rpc('ledger_me');$('identity').textContent=`${me.name} · ${me.email} · ${me.role}`;$('login').hidden=true;$('logout').hidden=false;$('refresh').hidden=false;
 $('workspace').hidden=!['owner','admin'].includes(me.role);$('member').hidden=me.role!=='member';$('inbox').hidden=me.role!=='owner';$('ownerNav').hidden=me.role!=='owner';$('auditPanel').hidden=me.role!=='owner';
 if(me.role==='member'){$('team').replaceChildren();$('jobs').replaceChildren();await myRequests();return;}
 const d=await rpc('ledger_admin_data');members=d.members;
 const prev=$('person').value;$('person').replaceChildren(el('option','Everyone'));$('person').firstChild.value='';members.forEach(m=>{const o=el('option',m.name);o.value=m.id;$('person').append(o);});$('person').value=prev;render();
 if(me.role==='owner')await inbox();
}
function start(){const p=$('period').value,d=new Date();d.setHours(0,0,0,0);if(p==='all')return new Date(0);if(p==='week')d.setDate(d.getDate()-(d.getDay()+6)%7);if(p==='month')d.setDate(1);if(p==='year')d.setMonth(0,1);return d;}
function sent(j){return j.history.find(h=>['Submitted','Applied'].includes(h.status))?.at;}
function render(){const from=start();let total=0,applied=0,accepted=0;$('team').replaceChildren();$('jobs').replaceChildren();const shown=members.filter(m=>!$('person').value||m.id===$('person').value);shown.forEach(m=>{const jobs=m.snapshot?.jobs||[],period=jobs.filter(j=>new Date(j.createdAt)>=from),n=jobs.filter(j=>sent(j)&&new Date(sent(j))>=from).length,a=period.filter(j=>j.history.at(-1).status==='Accepted').length;total+=period.length;applied+=n;accepted+=a;const tr=el('tr');[`${m.name} · ${m.role}`,period.length,n,a,m.synced_at?new Date(m.synced_at).toLocaleString():'Never synced'].forEach(v=>tr.append(el('td',v)));const td=el('td');if(me.role==='owner'&&m.role!=='owner'){const b=el('button',m.role==='admin'?'Revoke admin':'Grant admin');b.onclick=()=>act(async()=>{await rpc('ledger_set_admin',{p_user:m.id,p_admin:m.role!=='admin'});await load();});td.append(b);}else td.textContent=m.role==='owner'?'Workspace owner':'—';tr.append(td);$('team').append(tr);period.forEach(j=>{const row=el('tr');[m.name,j.title,j.company,j.history.at(-1).status].forEach(v=>row.append(el('td',v)));const cell=el('td'),b=el('button','View journey');b.onclick=()=>{$('history').replaceChildren();j.history.forEach(h=>{const d=el('div');d.className='event';d.append(el('strong',h.status),el('p',new Date(h.at).toLocaleString()),el('p',h.note));$('history').append(d);});$('detail').showModal();};cell.append(b);row.append(cell);$('jobs').append(row);});});$('stats').replaceChildren();[['Members',shown.length],['Jobs tracked',total],['Applications sent',applied],['Accepted',accepted]].forEach(([label,value])=>{const d=el('div');d.className='stat';d.append(el('span',label),el('strong',value));$('stats').append(d);});}
async function myRequests(){const rows=await rpc('ledger_my_requests');$('myRequests').replaceChildren();for(const r of rows)$('myRequests').append(el('p',`${new Date(r.created_at).toLocaleString()} · ${r.status}`));}
async function inbox(){const data=await rpc('ledger_inbox');$('inboxCount').textContent=`(${data.notices.filter(n=>!n.read_at).length} unread)`;$('requests').replaceChildren();for(const r of data.requests){const d=el('div');d.className='notice';d.append(el('strong',r.name+' · '+r.email),el('p',r.reason));for(const [label,approve]of [['Approve',true],['Reject',false]]){const b=el('button',label);b.onclick=()=>act(async()=>{await rpc('ledger_decide_admin',{p_request:r.id,p_approve:approve});await load();});d.append(b);}$('requests').append(d);}if(!data.requests.length)$('requests').append(el('p','No pending admin requests.'));
 $('notices').replaceChildren();for(const n of data.notices){const d=el('div');d.className='notice';d.append(el('span',n.message+' · '+new Date(n.created_at).toLocaleString()));if(!n.read_at){const b=el('button','Mark read');b.onclick=()=>act(async()=>{await rpc('ledger_read_notice',{p_id:n.id});await inbox();});d.append(b);}$('notices').append(d);}
 $('audit').replaceChildren();for(const a of data.audit){const name=members.find(m=>m.id===a.target)?.name||a.target;$('audit').append(el('p',`${new Date(a.created_at).toLocaleString()} · ${a.action} · ${name}`));}}
$('googleLogin').onclick=()=>act(async()=>{if(extension){if(!await chrome.permissions.request({origins:[projectURL()+'/*']}))throw Error('Workspace permission is required');const r=await chrome.runtime.sendMessage({type:'googleLogin'});if(r.error)throw Error(r.error);await load();}else{const flow=await beginGoogle(location.origin+location.pathname);sessionStorage.setItem('ledgerFlow',JSON.stringify(flow));location.assign(flow.url);}});
$('requestForm').onsubmit=e=>{e.preventDefault();act(async()=>{await rpc('ledger_request_admin',{p_reason:$('reason').value});$('reason').value='';await myRequests();$('message').textContent='Request sent. The owner will approve or reject it.';});};
$('refresh').onclick=()=>act(load);$('period').onchange=render;$('person').onchange=render;$('close').onclick=()=>$('detail').close();
$('logout').onclick=()=>act(async()=>{try{if(extension)await chrome.runtime.sendMessage({type:'logout'});else await cloud.logout();}finally{location.replace(location.pathname);}});
async function init(){if(!configured()){$('googleLogin').disabled=true;$('setup').textContent='Google sign-in setup is pending. Configure the Supabase project in config.js.';return;}
 if(!extension&&new URL(location.href).searchParams.has('code')){const raw=sessionStorage.getItem('ledgerFlow');sessionStorage.removeItem('ledgerFlow');const returned=location.href;history.replaceState(null,'',location.pathname);if(!raw)throw Error('Start sign-in again from this tab');await cloud.finish(returned,JSON.parse(raw));}
 if(extension){const r=await chrome.runtime.sendMessage({type:'state'});if(r.data?.user)await load();}else if(await cloud.storage.get())await load();}
init().catch(e=>{$('workspace').hidden=true;$('message').textContent=e.message;});
setInterval(()=>{if(me)load().catch(e=>{$('workspace').hidden=true;$('message').textContent=e.message;});},60000);
