import {projectURL} from './auth.js';
import {statuses,appliedDate,periodStart} from './core.js';
const $=id=>document.getElementById(id);let state,all=[],editing=null,selected=null;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
async function api(type,data={}){let timer;try{const r=await Promise.race([chrome.runtime.sendMessage({type,...data}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('ApplyLedger did not respond. Reload the extension on chrome://extensions, then reopen this dashboard.')),type==='googleLogin'?600000:15000);})]);if(!r||r.error)throw Error(r?.error||'The background worker is unavailable. Reload ApplyLedger on chrome://extensions.');return r.data;}finally{clearTimeout(timer);}}
function report(e){$('message').textContent=e.message||e;}
async function action(fn){try{$('message').textContent='';await fn();}catch(e){report(e);}}
const option=(value,label)=>{const o=el('option',label);o.value=value;return o;};
async function load(){state=await api('state');$('workspace').hidden=!state.user;$('logout').hidden=!state.user;$('auth').hidden=!!state.user;$('auth').replaceChildren();if(!state.user){$('auth').append(el('h2','Your job search, connected'),el('p','Sign in with your Google account to track your applications. Everyone joins as a member; administrator access requires owner approval.'));const b=el('button','Sign in with Google','google-button');b.disabled=!state.configured;b.onclick=()=>action(async()=>{const origin=projectURL();if(!await chrome.permissions.request({origins:[origin+'/*']}))throw Error('Workspace access permission is required for sign-in');b.disabled=true;try{await api('googleLogin');await load();}finally{b.disabled=false;}});$('auth').append(b);if(!state.configured)$('auth').append(el('p','Setup pending: configure the Supabase project in config.js.','muted'));$('auth').append(el('p','OAuth redirect for setup: '+state.redirect,'muted'));return;}
 $('identity').textContent=`${state.user.name} · ${state.user.role} · Google account`;
 $('accountEmail').textContent=state.user.email;
 $('adminPage').hidden=!['admin','owner'].includes(state.user.role);
 $('enableNotifications').hidden=state.user.role!=='owner';
 $('requestArea').hidden=state.user.role!=='member';

 all=state.jobs.map(j=>({...j,owner:state.profiles.find(p=>p.id===j.profileId)?.name||'Unknown',ownerKey:'local:'+j.profileId,imported:false}));for(const [key,s]of Object.entries(state.imports))all.push(...s.jobs.map(j=>({...j,owner:s.profile.name,ownerKey:key,imported:true})));
 const old=$('person').value;$('person').replaceChildren(option('','All available users'));const people=new Map();state.profiles.filter(p=>state.user.role==='admin'||p.id===state.user.id).forEach(p=>people.set('local:'+p.id,p.name));Object.entries(state.imports).forEach(([key,s])=>people.set(key,s.profile.name+' (imported)'));for(const [key,name]of people)$('person').append(option(key,name));if(people.has(old))$('person').value=old;
 render();await syncInfo();if(state.user.role==='member')await requestHistory();}

function render(){const p=$('period').value,start=p==='all'?new Date(0):periodStart(p),search=$('search').value.toLowerCase();const base=all.filter(j=>(!$('person').value||j.ownerKey===$('person').value)&&(!search||(j.title+' '+j.company).toLowerCase().includes(search))&&(!$('statusFilter').value||j.history.at(-1).status===$('statusFilter').value));const jobs=base.filter(j=>new Date(j.createdAt)>=start);const submitted=base.filter(j=>appliedDate(j)&&new Date(appliedDate(j))>=start);
 $('stats').replaceChildren();for(const [name,value,caption]of [['Jobs tracked',jobs.length,'Started in this period'],['Applications sent',submitted.length,'First submitted / applied in period'],['Active journeys',jobs.filter(j=>!['Rejected','Withdrawn','Accepted'].includes(j.history.at(-1).status)).length,'Of jobs started in period'],['Accepted',jobs.filter(j=>j.history.at(-1).status==='Accepted').length,'Of jobs started in period']]){const d=el('div',undefined,'stat');d.append(el('span',name),el('strong',value),el('span',caption,'muted'));$('stats').append(d);}
 $('chart').replaceChildren();const days=Array.from({length:14},(_,i)=>{const d=periodStart('day');d.setDate(d.getDate()-13+i);const end=new Date(d);end.setDate(end.getDate()+1);return {d,n:base.filter(j=>appliedDate(j)&&new Date(appliedDate(j))>=d&&new Date(appliedDate(j))<end).length};});const max=Math.max(1,...days.map(d=>d.n));days.forEach(({d,n})=>{const b=el('div',undefined,'bar');const bar=el('i');bar.style.height=(n/max*110)+'px';b.title=d.toLocaleDateString()+': '+n;b.append(el('span',n),bar,el('span',d.getDate()));$('chart').append(b);});
 $('team').replaceChildren();const counts=new Map();for(const j of submitted){const v=counts.get(j.ownerKey)||{name:j.owner,count:0};v.count++;counts.set(j.ownerKey,v);}for(const v of [...counts.values()].sort((a,b)=>b.count-a.count)){const row=el('div',undefined,'teamrow');row.append(el('span',v.name),el('strong',v.count));$('team').append(row);}if(!counts.size)$('team').append(el('p','No applications sent in this period.','muted'));
 $('rows').replaceChildren();$('count').textContent=`(${jobs.length})`;$('empty').hidden=!!jobs.length;for(const j of jobs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){const tr=el('tr'),role=el('td');role.append(el('strong',j.title));if(j.url){const a=el('a',j.company);a.href=j.url;a.target='_blank';a.rel='noopener noreferrer';role.append(a);}else role.append(el('span',j.company));const status=el('td');status.append(el('span',j.history.at(-1).status,'badge'));const buttons=el('td');const view=el('button','Journey');view.onclick=()=>detail(j);buttons.append(view);if(!j.imported&&j.profileId===state.user.id&&j.source==='manual'){const edit=el('button','Edit');edit.onclick=()=>editor(j);buttons.append(edit);}tr.append(role,el('td',j.owner+(j.imported?' (imported)':'')),el('td',new Date(j.createdAt).toLocaleDateString()),status,el('td',j.source==='auto'?'Locked Auto':'Manual'),buttons);$('rows').append(tr);}}
function editor(j){editing=j?.id||null;$('editorTitle').textContent=j?'Edit manual entry':'Add job to track';for(const k of ['title','company','url'])$('jobForm').elements[k].value=j?.[k]||'';$('editor').showModal();}
function detail(j){selected=j.id;$('detailTitle').textContent=j.title+' · '+j.company;$('history').replaceChildren();for(const h of j.history){const d=el('div',undefined,'event');d.append(el('strong',h.status),el('div',new Date(h.at).toLocaleString(),'muted'),el('p',h.note));$('history').append(d);}$('statusForm').hidden=j.imported||j.profileId!==state.user.id;$('newStatus').value=j.history.at(-1).status;$('note').value='';$('detail').showModal();}
statuses.forEach(s=>{$('statusFilter').append(option(s,s));$('newStatus').append(option(s,s));});for(const id of ['period','person','statusFilter'])$(id).onchange=render;$('search').oninput=render;
$('new').onclick=()=>editor();$('cancelEdit').onclick=()=>$('editor').close();$('closeDetail').onclick=()=>$('detail').close();$('logout').onclick=()=>action(async()=>{await api('logout');await load();});
$('jobForm').onsubmit=e=>{e.preventDefault();action(async()=>{const data=Object.fromEntries(new FormData(e.target));await api(editing?'edit':'add',{id:editing,data});$('editor').close();await load();});};
$('statusForm').onsubmit=e=>{e.preventDefault();action(async()=>{await api('status',{id:selected,status:$('newStatus').value,note:$('note').value});$('detail').close();await load();});};
$('export').onclick=()=>action(async()=>{const data=await api('export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=`applyledger-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
load().catch(report);

async function syncInfo(){if(!state?.user)return;const info=await api('syncInfo');$('syncState').textContent=info.message+(info.lastSync?' · Last successful sync: '+new Date(info.lastSync).toLocaleString():'');}
$('syncNow').onclick=()=>action(async()=>{await api('syncNow');report('Sync requested. Offline changes retry automatically.');});
$('adminPage').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('admin.html')});
$('enableNotifications').onclick=()=>action(async()=>{if(await chrome.permissions.request({permissions:['notifications']})){report('Owner notifications enabled. Alerts arrive while Chrome is running.');await api('syncNow');}});
async function requestHistory(){const requests=await api('myRequests');$('requestHistory').replaceChildren();for(const r of requests)$('requestHistory').append(el('p',`${new Date(r.created_at).toLocaleString()} · ${r.status}`,'muted'));}
$('requestForm').onsubmit=e=>{e.preventDefault();action(async()=>{await api('requestAdmin',{args:{p_reason:$('requestReason').value}});$('requestReason').value='';await requestHistory();report('Request sent to the workspace owner.');});};
setInterval(()=>{if(state?.user)syncInfo().catch(()=>{});},5000);
