const $=id=>document.getElementById(id);
const loadingTimer=setTimeout(()=>{$('who').textContent='The extension is not responding. Reload ApplyLedger on chrome://extensions, then reopen this popup.';},10000);
chrome.runtime.sendMessage({type:'state'}).then(r=>{if(!r||r.error)throw Error(r?.error||'No response from the background worker');$('who').textContent=r.data?.user?`Signed in as ${r.data.user.name}`:'Open the dashboard to sign in with Google.';}).catch(e=>{$('who').textContent='Unable to start ApplyLedger: '+e.message+'. Reload the extension on chrome://extensions.';}).finally(()=>clearTimeout(loadingTimer));
$('open').onclick=()=>chrome.runtime.openOptionsPage();
async function site(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const u=new URL(tab.url);if(!['https:','http:'].includes(u.protocol))throw Error('Open a regular website first.');return {tab,pattern:u.origin+'/*',id:'site-'+Array.from(u.origin).map(c=>c.charCodeAt(0).toString(16)).join('')};}
$('track').onclick=async()=>{try{const {tab,pattern,id}=await site();if(!await chrome.permissions.request({origins:[pattern]}))throw Error('Site permission was not granted');const scripts=await chrome.scripting.getRegisteredContentScripts({ids:[id]});if(!scripts.length)await chrome.scripting.registerContentScripts([{id,matches:[pattern],js:['content.js'],runAt:'document_idle',persistAcrossSessions:true}]);await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']});$('result').textContent='Tracking enabled. Check the dashboard after submitting.';}catch(e){$('result').textContent=e.message;}};
$('stop').onclick=async()=>{try{const {pattern,id}=await site();await chrome.scripting.unregisterContentScripts({ids:[id]});await chrome.permissions.remove({origins:[pattern]});$('result').textContent='Tracking disabled. Reload this page to stop the existing page listener.';}catch(e){$('result').textContent=e.message;}};

$('save').onclick=async()=>{try{const {tab}=await site();const [r]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>({title:document.querySelector('h1')?.innerText||document.title,company:location.hostname,url:location.href})});const response=await chrome.runtime.sendMessage({type:'savePage',data:r.result});if(response.error)throw Error(response.error);$('result').textContent='Job saved. Open its journey to mark In progress or add notes.';}catch(e){$('result').textContent=e.message;}};
